# Generated by Django 2.1.2 on 2020-06-30 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'ACM Transactions on Privacy and Security (TOPS)'), ('2', 'ACM Transactions on Information Systems (TOIS)'), ('3', 'ACM Transactions on Management Information Systems'), ('4', 'Business & Information Systems Engineering'), ('5', 'Business Research'), ('6', 'Business Strategy and the Environment'), ('7', 'CIO'), ('8', 'Computerwoche'), ('9', 'Decision Sciences'), ('10', 'DuD - Datenschutz und Datensicherheit'), ('11', 'Electronic Markets'), ('12', 'HMD Praxis der Wirtschaftsinformatik'), ('13', 'IEEE Transactions on Engineering Management'), ('14', 'Information Systems Journal'), ('15', 'Journal of Business Economics'), ('16', 'Management Science'), ('17', 'Wirtschaftsinformatik & Management'), ('18', 'Information Systems Research'), ('19', 'Journal of Information Technology Theory and Application (JITTA)'), ('20', 'Journal of the Association for Information Systems'), ('21', 'Communications of the AIS'), ('22', 'MIS Quarterly Executive')], max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
