# Generated by Django 3.0.7 on 2020-07-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200706_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journals',
            old_name='my_field',
            new_name='not_interested',
        ),
    ]
