# Generated by Django 3.0.7 on 2020-07-06 13:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200706_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='not_interested',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'ACM Transactions on Privacy and Security (TOPS)'), ('2', 'ACM Transactions on Information Systems (TOIS)'), ('3', 'ACM Transactions on Management Information Systems'), ('4', 'Business & Information Systems Engineering'), ('5', 'Business Research'), ('6', 'Business Strategy and the Environment'), ('7', 'CIO'), ('8', 'Computerwoche'), ('9', 'Decision Sciences'), ('10', 'DuD - Datenschutz und Datensicherheit'), ('11', 'Electronic Markets'), ('12', 'HMD Praxis der Wirtschaftsinformatik'), ('13', 'IEEE Transactions on Engineering Management'), ('14', 'Information Systems Journal'), ('15', 'Journal of Business Economics'), ('16', 'Management Science'), ('17', 'Wirtschaftsinformatik & Management'), ('18', 'Information Systems Research'), ('19', 'Journal of Information Technology Theory and Application (JITTA)'), ('20', 'Journal of the Association for Information Systems'), ('21', 'Communications of the AIS'), ('22', 'MIS Quarterly Executive')], max_length=56, null=True),
        ),
    ]
