# Generated by Django 3.0.7 on 2020-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200706_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=20)),
                ('issOld', models.CharField(max_length=50)),
                ('date_latest_issue', models.CharField(max_length=100)),
                ('crawlable', models.IntegerField(max_length=1)),
            ],
        ),
    ]
