# Generated by Django 3.0.7 on 2020-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='crawlable',
            field=models.IntegerField(),
        ),
    ]
