# Generated by Django 3.0.7 on 2020-07-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200707_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journals',
        ),
    ]
